### ISSUE TITLE
Come mantenere i dati relativi ai singoli punti 

### ISSUE THREAD

**Issue by RinoAmilcare85** [gustavowillam/SmartMapPlugin#89]
Buongiorno Gustav, sono Venturo e sono un ricercatore dell'Università della Basilicata (Matera). Sto lavorando sulla mappatura di Land Suitability della regione Basilicata per la coltivazione di uva da vino. Per fare questo sto utilizzando SmartMap per effettuare il Kriging di alcuni dati puntiformi, come ad esempio ho 44 punti georeferenziati e per ognuno di loro un indice di Fregoni, dopo aver importato i punti in SmartMap:
![1](https://github.com/user-attachments/assets/060642f1-e498-470f-bd33-70b11d57a343)
e aver caricato il poligono del perimetro regionale:
![2](https://github.com/user-attachments/assets/7335685d-5d0b-4dc5-9e8b-16fea047430d)
creo l'interpolazione lasciando tutti i parametri che il plugin mi crea di default:
![3](https://github.com/user-attachments/assets/dfc2cabf-2407-4d03-9a4b-0a5c40ca40b8)
Il problema è che il kriging non ha come range di dati gli stessi forniti, cioè se i miei dati puntuali per Fregoni vanno da 0 a 109415,7987 vorrei che anche il Kriging mi dia un risultato compreso in questo range. Mi potresti gentilmente aiutare? Grazie mille
![4](https://github.com/user-attachments/assets/f7808bdd-1156-4c5c-8b71-f45c1930335d)
![5](https://github.com/user-attachments/assets/d68178e1-efa4-491b-93a7-9322979d4d53)

**Comment by gustavowillam** [comment]
Hello Venturo.

Analyzing the images, your data shows low spatial correlation (Moran's I equal to 0.002) with a P-Value of 0.47. In Figure 2, you can see that only the easternmost point has a high value, approximately around 100,000, and a point to the northwest around 50,000. These 2 points are probably outliers in your database. I suggest removing them using the (Eliminate Outliers) functionality by selecting this option in the Data tab (first interface of the plugin). That is why, when interpolating, your map is turning green in the east and northwest regions of the map (Figure 3). After interpolation, your interpolated map is showing values ​​ranging from -272.979950 to 33,633.246094 (Figures 4 and 5). I suggest reviewing your data to check for the presence of negative values ​​of the target variable (Fregoni) in your set of sampled points. The R2 of the semivariogram fit is very low (R2 = 0.215 in Figure 3). In the Interpolation tab of the plugin, check the best semivariogram fit (Variogram tab) to better adjust the Kriging parameters. This R2 value is low due to the low spatial dependence of your collected data. Remember that Kriging is very sensitive to the spatial dependence between the sampled points.
